import styles from "./SearchMenu.module.scss";

const SearchMenu = () => {
  //categories below to be generated by mapping through categories array
  //current options are just placeholders
  return (
    <>
      <div className={styles.search__container}>
        <label className={styles.label} forHTML="category">
          Game Category{" "}
        </label>
        <select className={styles.select}>
          {/* categories to be mapped from twitch server categories */}
          <option className={styles.options} value="1">
            Placeholder 1
          </option>
          <option className={styles.options} value="2">
            Placeholder 2
          </option>
          <option className={styles.options} value="3">
            Placeholder 3
          </option>
          <option className={styles.options} value="4">
            Placeholder 4
          </option>
          <option className={styles.options} value="5">
            Placeholder 5
          </option>
        </select>
      </div>
    </>
  );
};

export default SearchMenu;

//import categories via getStaticProps from the twitch API
